# Generated by Django 5.1.7 on 2025-04-10 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.IntegerField(primary_key=True, serialize=False)),
                ('module_title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Modules',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('unit_title', models.CharField(max_length=100)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.module')),
            ],
            options={
                'db_table': 'Units',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('problem_type', models.CharField(choices=[('Multi-Select', 'Multi-Select'), ('True-False', 'True-False')], max_length=20)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('choice1', models.CharField(max_length=100)),
                ('choice2', models.CharField(max_length=100)),
                ('choice3', models.CharField(blank=True, max_length=100, null=True)),
                ('correct_answer', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.unit')),
            ],
            options={
                'db_table': 'Problems',
            },
        ),
    ]
