-- Drop Tables
DROP TABLE IF EXISTS Submissions;
DROP TABLE IF EXISTS Progress;
DROP TABLE IF EXISTS Messages;
DROP TABLE IF EXISTS Feedbacks;

DROP TABLE IF EXISTS Students;
DROP TABLE IF EXISTS Instructors;
DROP TABLE IF EXISTS Admins;

DROP TABLE IF EXISTS Problems;
DROP TABLE IF EXISTS Units;
DROP TABLE IF EXISTS Modules;

DROP TABLE IF EXISTS Users;